### ISSUE TITLE
navigation frontmatter?

### ISSUE THREAD

**Issue by kf0mlb** [dbohdan/caddy-markdown-site#2]
Is there a way to put a set of links in the frontmatter and use them for a sidebar nav?  If I put a basic list of text in the frontmatter, it loads fine:

```
---
title: test
nav:
 - 1
 - 2
 - 3
```

But if I turn those into links, the page won't load.

```
title: test
nav:
 - [1](www.google.com)
 - [2](www.duckduckgo.com)
 - [3](www.altavista.com)
```

**Comment by dbohdan** [comment]
The front matter with the links is not valid YAML. Put each list item in quotes to fix it.

I think a [multiline string](https://yaml-multiline.info/) would be a better choice here than a list. You could then use the string in the template with `{{ markdown $markdownFile.Meta.nav }}`.

**Comment by kf0mlb** [comment]
I forgot to come back and comment. A plain multiline yaml, using html in the string, did exactly what I wanted.  Thank you.
